music_duel_environment: &music_duel_environment
  adapter: postgresql
  encoding: unicode
  pool: 5 

development:
  database: music_duel_dev
  host: localhost
  SLOT_DB_PORT: 3306
  <<: *music_duel_environment

test:
  database: music_duel_test
  host: localhost
  SLOT_DB_PORT: 3306
  <<: *music_duel_environment

production:
  <<: *music_duel_environment
